services:
  db:
    image: postgres:16.0-alpine
    container_name: password_keeper_db
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: